ACM-14356: Edge Management dev-preview info
stolostron/stolostron pull request #20
Opened 2024-10-10 09:35 UTC by oglok

Description of Edge Management (project Flight Control) for ACM 2.12 dev-preview.

2024-10-10 09:50 UTC, oglok commented
https://issues.redhat.com/browse/ACM-12519

2024-10-10 09:52 UTC, avishayt commented on dev-preview/README.md
> +Edge Management aims to provide simple, scalable, and secure management of edge devices and applications. Users declare the operating system version, host configuration, and set of applications they
I would mention MicroShift/RHDE up front.

2024-10-10 10:11 UTC, mangelajo approved these changes
/lgtm

2024-10-10 10:46 UTC, fzdarsky commented on dev-preview/README.md
> +Edge Management aims to provide simple, scalable, and secure management of edge devices and applications. Users declare the operating system version, host configuration, and set of applications they
```suggestion
Edge Management aims to provide simple, scalable, and secure management of edge servers or devices running image-mode RHEL / RHDE and applications on Podman or MicroShift. Users declare the target operating system version, host configuration, and set of applications they want to run similarly to how they would on edge clusters with OpenShift. Edge Management further debuts fleet management, enabling users to specify device templates that Edge Management automatically rolls out to groups of devices and reports progress and health status on.
```

2024-10-10 10:50 UTC, mangelajo requested changes
see @fzdarsky comments

2024-10-10 11:39 UTC, oglok commented
Comments addressed! Thanks @avishayt @fzdarsky @mangelajo

2024-10-11 14:34 UTC, jnpacker commented
/lgtm

2024-10-11 14:35 UTC, jnpacker commented
/approve

2024-10-11 14:53 UTC, jnpacker approved these changes
Looks good to me.

2024-10-11 14:55 UTC, merged